assets:     
  - discimport.sql.gz
steps:
  - name: Probo CI site setup
    plugin: Drupal
    makeFile: build-discimport.make
    database: discimport.sql.gz
    databaseGzipped: true
    databaseUpdates: true
    clearCaches: true
  - name: Make directory for site
    command: 'mkdir /var/www/html/sites/discimport.dk; mkdir /var/www/html/sites/discimport.dk/files; mkdir /var/www/html/sites/discimport.dk/private; mkdir /var/www/html/sites/discimport.dk/private/temp'
  - name: Fix permissions
    command: 'chown -R www-data:www-data /var/www/html/sites/discimport.dk; chmod 777 -R /var/www/html/sites/discimport.dk'
  - name: Generate login link
    command: 'drush --root="/var/www/html" uli'
  - name: Enable stage_file_proxy
    command: 'drush --root="/var/www/html" en stage_file_proxy -y; drush variable-set stage_file_proxy_origin "http://discimport.dk"'
  - name: Reroute e-mails
    command: 'drush --root="/var/www/html" en reroute_email -y; drush variable-set reroute_email_enable 1; drush variable-set reroute_email_address "lars@intraface.dk"'
  - name: Disable certain modules
    command: 'drush --root="/var/www/html" pm-disable googleanalytics'
