assets:     
  - discimport.sql.gz
steps:
  - name: Probo CI site setup
    plugin: Drupal
    makeFile: build-discimport.make
    database: discimport.sql.gz
    databaseGzipped: true
    databaseUpdates: true
    clearCaches: true
  - name: Generate login link
    command: 'drush --root="/var/www/html" uli'
  - name: Enable stage_file_proxy
    command: 'drush --root="/var/www/html" en stage_file_proxy -y'
    command: 'drush variable-set stage_file_proxy_origin "http://discimport.dk"'
