language: php
sudo: false

php:
  - 5.5

mysql:
  database: drupal
  username: root
  encoding: utf8

matrix:
  fast_finish: true
  include:
    - php: 5.6

# Cache Composer & Drush directories.
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.drush/cache

install:
  - "mysql -e 'create database drupal;'"

  # Install latest Drush 6.
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "drush/drush:6.*"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  - drush make build-discimport.make ../discimport.dk
  - cd ../discimport.dk
  - chmod -R 777 sites/all/modules

before_script:
  - drush si commerce_kickstart --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=DISCIMPORT@2012 --site-mail=admin@example.com --site-name="discimport.dk" --yes
  - drush en discimport_deploy -y
  - drush cc all --yes
  - cd ../discimport-build

script: 
  - test -d ../discimport.dk/profiles/commerce_kickstart
  - test -d ../discimport.dk/sites/all/modules/contrib
